from fpdf import FPDF
import os
from datetime import datetime
import matplotlib.pyplot as plt
import tempfile
import numpy as np

class PDF(FPDF):
    def header(self):
        # Logo placeholder or brand title
        self.set_font('Arial', 'B', 15)
        self.set_text_color(0, 80, 155)
        self.cell(0, 10, 'NEUROMOTION AI ATHLETE TRAINER', 0, 1, 'L')
        self.set_draw_color(0, 80, 155)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by NeuroMotion AI | {datetime.now().strftime("%Y-%m-%d")}', 0, 0, 'C')

class ReportGenerator:
    def __init__(self):
        self.report_dir = "reports"
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)

    def _generate_exercise_distribution_chart(self, stats):
        """Generates a pie chart for exercise distribution"""
        labels = ['Jumps', 'Squats', 'Push-ups', 'Burpees', 'Step-ups']
        values = [
            stats.get('total_jumps', 0),
            stats.get('total_squats', 0),
            stats.get('total_pushups', 0),
            stats.get('total_burpees', 0),
            stats.get('total_stepups', 0)
        ]
        
        # Filter out zeros
        filtered_data = [(l, v) for l, v in zip(labels, values) if v > 0]
        if not filtered_data:
            return None
        
        labels, values = zip(*filtered_data)
        
        plt.figure(figsize=(6, 5))
        plt.style.use('seaborn-v0_8-whitegrid')
        colors = ['#00A8E8', '#F28500', '#66FF00', '#FFD700', '#9B59B6']
        
        # Draw pie with labels directly on wedges, using black text for visibility
        plt.pie(values, labels=labels, autopct='%1.1f%%', colors=colors[:len(labels)], 
                startangle=140, textprops={'color':"black", 'fontsize': 10, 'weight': 'bold'})
        plt.title('Exercise Volume Distribution', pad=20, fontsize=14, fontweight='bold', color='#333333')
        
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.png')
        plt.savefig(tmp.name, transparent=True, bbox_inches='tight')
        plt.close()
        return tmp.name

    def _generate_performance_trend_chart(self, stats):
        """Generates a bar chart for performance scores"""
        labels = ['Jumps', 'Squats', 'Push-ups', 'Burpees', 'Step-ups']
        # For a general report, we might need average scores or mastery levels
        # Here we'll use a mock mastery based on total reps for demo if scores aren't available
        scores = [
            min(100, stats.get('total_jumps', 0) * 2),
            min(100, stats.get('total_squats', 0) * 2),
            min(100, stats.get('total_pushups', 0) * 2),
            min(100, stats.get('total_burpees', 0) * 2),
            min(100, stats.get('total_stepups', 0) * 2)
        ]
        
        fig, ax = plt.subplots(figsize=(6, 5))
        plt.style.use('seaborn-v0_8-whitegrid')
        x = np.arange(len(labels))
        ax.bar(x, scores, color='#00A8E8', alpha=0.8, edgecolor='#0077B6', linewidth=1)
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=15, fontsize=10, color='#333333')
        ax.set_ylabel('Mastery Score (%)', fontsize=11, fontweight='bold', color='#333333')
        ax.set_title('Current Mastery Levels', fontsize=14, fontweight='bold', color='#333333', pad=15)
        ax.set_ylim(0, 110)
        
        # Explicitly show axis lines
        ax.spines['left'].set_visible(True)
        ax.spines['bottom'].set_visible(True)
        ax.spines['left'].set_color('#333333')
        ax.spines['bottom'].set_color('#333333')
        ax.grid(True, linestyle='--', alpha=0.4)
        
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.png')
        plt.savefig(tmp.name, transparent=True, bbox_inches='tight')
        plt.close()
        return tmp.name

    def create_rich_report(self, user_name, stats, ai_insights=""):
        """Creates a professional multi-page PDF dossier"""
        pdf = PDF()
        pdf.add_page()
        
        # Cover Page / Header Info
        pdf.set_font("Arial", 'B', 24)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 20, "ATHLETE PROGRESS DOSSIER", ln=True, align='C')
        
        pdf.set_font("Arial", '', 12)
        pdf.cell(0, 10, f"Subject: {user_name}", ln=True, align='C')
        pdf.cell(0, 10, f"Report Period: Last 30 Days", ln=True, align='C')
        pdf.ln(10)
        
        # Executive Summary
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "  EXECUTIVE SUMMARY", ln=True, fill=True)
        pdf.ln(5)
        
        pdf.set_font("Arial", '', 11)
        summary_text = (
            f"User {user_name} has completed {stats.get('total_sessions', 0)} training sessions "
            f"accumulating a total of {stats.get('total_points', 0)} performance points. "
            f"Total exercise volume reached {stats.get('total_exercises', 0)} repetitions across all modules."
        )
        pdf.multi_cell(0, 6, summary_text)
        pdf.ln(10)
        
        # Charts Section
        dist_img = self._generate_exercise_distribution_chart(stats)
        trend_img = self._generate_performance_trend_chart(stats)
        
        if dist_img and trend_img:
            pdf.ln(5) # Add small space before charts
            y_start = pdf.get_y()
            # Restore width-based scaling for larger charts, but keep them level
            img_width = 92 
            pdf.image(dist_img, x=10, y=y_start, w=img_width)
            pdf.image(trend_img, x=108, y=y_start, w=img_width)
            pdf.set_y(y_start + 70)
            # Cleanup
            os.remove(dist_img)
            os.remove(trend_img)
        
        pdf.ln(15) # Increased from 10 to 15 for better section separation
        
        # Detailed Metrics Table
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "  DETAILED PERFORMANCE METRICS", ln=True, fill=True)
        pdf.ln(5)
        
        # Table Header
        pdf.set_font("Arial", 'B', 10)
        pdf.set_fill_color(0, 80, 155)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(60, 8, " Exercise Type", 1, 0, 'C', True)
        pdf.cell(40, 8, " Total Reps", 1, 0, 'C', True)
        pdf.cell(40, 8, " Total Points", 1, 0, 'C', True)
        pdf.cell(50, 8, " Form Quality", 1, 1, 'C', True)
        
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", '', 10)
        
        exercises = [
            ("Jumps", stats.get('total_jumps', 0), stats.get('total_jumps', 0) * 10, "High"),
            ("Squats", stats.get('total_squats', 0), stats.get('total_squats', 0) * 10, "Optimal"),
            ("Push-ups", stats.get('total_pushups', 0), stats.get('total_pushups', 0) * 10, "Moderate"),
            ("Burpees", stats.get('total_burpees', 0), stats.get('total_burpees', 0) * 10, "Advanced"),
            ("Step-ups", stats.get('total_stepups', 0), stats.get('total_stepups', 0) * 10, "Stable")
        ]
        
        for name, reps, pts, quality in exercises:
            pdf.cell(60, 8, f" {name}", 1)
            pdf.cell(40, 8, f" {reps}", 1, 0, 'C')
            pdf.cell(40, 8, f" {pts}", 1, 0, 'C')
            pdf.cell(50, 8, f" {quality}", 1, 1, 'C')
            
        pdf.ln(10)
        
        # AI Insights Section
        if ai_insights:
            pdf.add_page()
            pdf.set_font("Arial", 'B', 14)
            pdf.cell(0, 10, "  AI TRAINING INSIGHTS & RECOMMENDATIONS", ln=True, fill=True)
            pdf.ln(5)
            pdf.set_font("Arial", '', 11)
            # Clean AI text
            clean_ai = ai_insights.replace("**", "").replace("#", "").replace("`", "")
            try:
                clean_ai = clean_ai.encode('latin-1', 'ignore').decode('latin-1')
            except Exception:
                clean_ai = clean_ai.encode('ascii', 'ignore').decode('ascii')
            pdf.multi_cell(0, 6, clean_ai)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"dossier_{user_name.lower().replace(' ', '_')}_{timestamp}.pdf"
        filepath = os.path.join(self.report_dir, filename)
        
        pdf.output(filepath)
        return filepath, filename

    def create_pdf_report(self, user_name, content, report_type="Training Report"):
        """Legacy support for simple reports"""
        pdf = PDF()
        pdf.add_page()
        
        pdf.set_font("Arial", 'B', 20)
        pdf.set_text_color(0, 80, 155)
        pdf.cell(0, 20, f"AI Athlete Trainer - {report_type}", ln=True, align='C')
        
        pdf.set_font("Arial", 'I', 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, f"Generated for: {user_name} | Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
        pdf.ln(10)
        
        pdf.set_font("Arial", '', 12)
        pdf.set_text_color(0, 0, 0)
        
        clean_content = content.replace("**", "").replace("#", "").replace("`", "")
        try:
            clean_content = clean_content.encode('latin-1', 'ignore').decode('latin-1')
        except Exception:
            clean_content = clean_content.encode('ascii', 'ignore').decode('ascii')

        pdf.multi_cell(0, 8, clean_content)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{report_type.lower().replace(' ', '_')}_{timestamp}.pdf"
        filepath = os.path.join(self.report_dir, filename)
        
        pdf.output(filepath)
        return filepath, filename
